import 'package:coach_link/firebase_options.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'app.dart';
import 'core/notifications/fcm_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Hive.initFlutter();
  await Hive.openBox<String>('bdui_schemas');

  await _initFirebase();

  runApp(const ProviderScope(child: CoachLinkApp()));
}

Future<void> _initFirebase() async {
  try {
    // firebase_options.dart is generated by `flutterfire configure`.
    // Until that is done, Firebase won't initialize and push notifications
    // won't work — but the rest of the app functions normally.
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
    debugPrint('[FCM] Firebase initialized');
  } catch (e) {
    debugPrint('[FCM] Firebase not configured — push notifications disabled. '
        'Run `flutterfire configure` to enable them. Error: $e');
  }
}
